#!/usr/bin/env bash
# Optional: local semantic + keyword search over your content vault with qmd.
#
# Installs qmd if missing, registers collections over content/ + skills/, embeds
# them, and installs an auto-sync post-commit hook so the index stays fresh.
# Idempotent. First run downloads ~2GB of models (cached in ~/.cache/qmd), so
# this is opt-in — the vault works fine without it.
#
#   ./scripts/qmd-setup.sh
#   qmd query "hooks that landed for launch posts"
#
# Agents can also search via the qmd MCP server (mcp__qmd__*).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"
SLUG="$(basename "$REPO_ROOT")"

if ! command -v qmd >/dev/null 2>&1; then
  echo "==> Installing qmd globally via npm..."
  npm install -g @tobilu/qmd
fi
QMD="$(command -v qmd)"; QMD_BIN_DIR="$(dirname "$QMD")"
echo "==> qmd: $QMD ($("$QMD" --version 2>/dev/null | head -1))"

add_collection() {  # <name> <path>
  local name="$1" path="$2" out
  [ -d "$REPO_ROOT/$path" ] || { echo "    skip '$name' (no $path)"; return 0; }
  if out="$(qmd collection add "$REPO_ROOT/$path" --name "$name" 2>&1)"; then
    echo "    created collection '$name' -> $path"
  elif printf '%s' "$out" | grep -qi 'already exists'; then
    echo "    collection '$name' already exists"
  else
    echo "    ERROR creating collection '$name': $out" >&2; return 1
  fi
}
echo "==> Collections"
add_collection "${SLUG}-content" "content"   # your drafts + published posts
add_collection "${SLUG}-skills"  "skills"    # the skill docs + your corpora

qmd context add "qmd://${SLUG}-content" "Content vault: drafts, published posts, ideas across LinkedIn/X/YouTube/newsletter/long-form." >/dev/null 2>&1 || true
qmd context add "qmd://${SLUG}-skills"  "Content Vault skills + your voice corpora and examples." >/dev/null 2>&1 || true

echo "==> Embedding (first run downloads models, cached in ~/.cache/qmd)"
qmd update
qmd embed

echo "==> Installing post-commit hook"
HOOK="$REPO_ROOT/.git/hooks/post-commit"
mkdir -p "$(dirname "$HOOK")"
cat > "$HOOK" <<HOOK_TEMPLATE
#!/usr/bin/env bash
# Auto-sync the qmd index after every commit. Generated by scripts/qmd-setup.sh.
# LOCAL-ONLY. Runs detached so commits never block; coalesces rapid commits.
set -u
export PATH="${QMD_BIN_DIR}:\$PATH"
command -v qmd >/dev/null 2>&1 || exit 0
CACHE="\$HOME/.cache/qmd"; LOG="\$CACHE/auto-sync.log"
LOCK="\$CACHE/auto-sync.${SLUG}.lock"; FLAG="\$CACHE/auto-sync.${SLUG}.dirty"
mkdir -p "\$CACHE"
REV="\$(git rev-parse --short HEAD 2>/dev/null || echo '?')"
: > "\$FLAG"
(
  mkdir "\$LOCK" 2>/dev/null || exit 0
  trap 'rmdir "\$LOCK" 2>/dev/null' EXIT
  unset GIT_DIR GIT_INDEX_FILE GIT_WORK_TREE GIT_PREFIX 2>/dev/null || true
  cd "${REPO_ROOT}" || exit 0
  while [ -f "\$FLAG" ]; do
    rm -f "\$FLAG"
    { echo "=== \$(date '+%Y-%m-%d %H:%M:%S') auto-sync (commit \$REV) ==="; ./scripts/qmd-refresh.sh; } >> "\$LOG" 2>&1
  done
) >/dev/null 2>&1 &
exit 0
HOOK_TEMPLATE
chmod +x "$HOOK"
echo "    installed: $HOOK"

echo "==> Done. qmd local search is ready."
echo "    Query: qmd query \"...\"   ·   Watch: tail -f ~/.cache/qmd/auto-sync.log"
